// =============================================================================
// provenance.ts — Editor Suite provenance types (#940, #939, #1458, #1457)
//
// Phase 1 — Provenance field schema + user_modified span tracking
// Phase 2 — Streaming diff + citation badge types
// Phase 3 — QuoteAnchor + drift detection
// Phase 4 — Caption Registry
//
// All types are append-only and forward-compatible with legacy un-provenanced
// content (every consumer must treat absence of a ProvenanceSpan as graceful
// fallback — no badge, no error).
// =============================================================================

// ── Phase 1 ───────────────────────────────────────────────────────────────────

/**
 * How a span entered the document. Used by citation badges to decide whether
 * to render: only 'quoted' and 'imported' spans earn a badge (#940, AC3).
 *
 *  ai       — generated by the AI model from internal knowledge
 *  user     — typed directly by the user
 *  imported — pulled in from an attached source document
 *  quoted   — an explicit quotation anchored to a source passage
 */
export type SpanOrigin = 'ai' | 'user' | 'imported' | 'quoted';

/**
 * Immutable provenance record attached to an AI-generated text span.
 * Created at generation time; never mutated — history entries are appended.
 */
export interface ProvenanceSpan {
  /** Stable identifier for the originating source document / passage. */
  source_id: string;
  /**
   * How the span entered the document (#940).
   * Drives badge visibility: badge rendered iff origin∈{'quoted','imported'}.
   */
  origin: SpanOrigin;
  /** Byte or character offset within source where the grounded span begins. */
  span_start: number;
  /** Byte or character offset within source where the grounded span ends (exclusive). */
  span_end: number;
  /** Model-reported confidence [0, 1]. Degrades when user_modified=true. */
  confidence: number;
  /** ISO 8601 timestamp of AI generation. */
  generated_at: string;
}

/**
 * Mutable wrapper stored on an editor node alongside the ProvenanceSpan.
 * Split and merge operations append a ProvenanceHistoryEntry; they do NOT
 * overwrite the original span — citation linkage is never destroyed.
 */
export interface ProvenanceState {
  /** Original provenance object from the AI generation event. */
  span: ProvenanceSpan;
  /**
   * True if the user has manually edited any character in this span.
   * Causes the displayed confidence to degrade; source_id link is preserved.
   */
  user_modified: boolean;
  /**
   * Append-only history of structural changes (split, merge).
   * Read by the audit trail — never deleted.
   */
  history: ProvenanceHistoryEntry[];
}

export type ProvenanceEventKind = 'split' | 'merge' | 'edit';

export interface ProvenanceHistoryEntry {
  kind: ProvenanceEventKind;
  /** ISO 8601 timestamp of the change. */
  at: string;
  /** For split: the sibling span that was created. */
  sibling_source_id?: string;
  /** For merge: the span that was consumed. */
  merged_source_id?: string;
}

// ── Phase 2 ───────────────────────────────────────────────────────────────────

/**
 * A single token-level diff event emitted by the streaming diff renderer.
 * kind=added: new token being inserted. kind=removed: token leaving the doc.
 * kind=context: unchanged surrounding token (for context display).
 */
export interface DiffToken {
  kind: 'added' | 'removed' | 'context';
  text: string;
  /**
   * Present on 'added' tokens when the streamed span has resolved a grounded
   * provenance object. Absent for ungrounded tokens — renders no badge.
   */
  provenance?: ProvenanceSpan;
}

/**
 * Inline citation badge data derived from a resolved ProvenanceSpan.
 * Pre-computed at streaming time; never re-derived at render time.
 * Only produced when origin∈{'quoted','imported'} (AC3).
 */
export interface CitationBadge {
  source_id: string;
  /** Mirrors ProvenanceSpan.origin — callers can assert this is quoted|imported. */
  origin: SpanOrigin;
  confidence: number;
  user_modified: boolean;
  /** Short display label (e.g. "Source 1", source title abbreviation). */
  label: string;
}

// ── Phase 3 ───────────────────────────────────────────────────────────────────

/**
 * Anchor that ties a quoted passage in the editor back to its origin in the
 * source document. Stored as a hidden span attribute.
 */
export interface QuoteAnchor {
  source_id: string;
  /** [start, end) character range within the source passage. */
  char_range: [number, number];
  /**
   * SHA-256 hex digest of the quoted text at anchoring time.
   * Used by the drift check: if the source content changes, the hash diverges.
   */
  hash_of_quoted_text: string;
}

/** Result of a drift check on document load. */
export interface DriftCheckResult {
  anchor: QuoteAnchor;
  drifted: boolean;
  /** Current hash of the source passage, for display in the drift warning. */
  current_hash: string;
}

// ── Phase 4 ───────────────────────────────────────────────────────────────────

/**
 * A single caption entry in the session-scoped Caption Registry.
 * Keyed by figureId — the registry deduplicates on insert.
 */
export interface CaptionEntry {
  /** Stable figure/table identifier (e.g. "fig-1", "table-3"). */
  figure_id: string;
  /** Human-readable caption text. */
  caption: string;
  /**
   * Back-link to the source document from which the figure/caption was pulled.
   * May be undefined for manually authored captions.
   */
  source_id?: string;
  /** ISO 8601 timestamp of first insertion. */
  registered_at: string;
}
