using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ato.Copilot.Core.Models.Tenancy.Attributes;

namespace Ato.Copilot.Core.Models.Compliance;

// ═══════════════════════════════════════════════════════════════════════════════
// Feature 076 — T012 / T013 — AI-Assisted OSCAL Control Statement Decomposition
// Two entities: OscalDecompositionDraft (one per control review session) and
// OscalDecompositionFragment (one per OSCAL statement-level fragment produced
// by the AI decomposition pass). Both are tenant-scoped.
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Enum ────────────────────────────────────────────────────────────────────

/// <summary>
/// Lifecycle state of an AI-generated OSCAL decomposition draft.
/// Human approval is required before fragments are written back to
/// <see cref="ControlImplementation.Narrative"/>.
/// </summary>
public enum DecompositionDraftStatus
{
    /// <summary>Draft has been generated and is awaiting human review.</summary>
    Pending,

    /// <summary>Draft was reviewed and approved; fragments were applied to ControlImplementation.</summary>
    Approved,

    /// <summary>Draft was discarded by the reviewer without being applied.</summary>
    Discarded,
}

// ─── Entities ────────────────────────────────────────────────────────────────

/// <summary>
/// Represents one AI-generated OSCAL decomposition attempt for a single
/// control narrative. A draft collects one or more <see cref="OscalDecompositionFragment"/>
/// children, each mapping to an OSCAL statement-level by-component entry.
/// </summary>
/// <remarks>
/// Feature 076 — T012.  One draft per (RegisteredSystemId, ControlId) in
/// <see cref="DecompositionDraftStatus.Pending"/> state at any time; prior
/// pending drafts are superseded when a new decomposition is requested.
/// </remarks>
[TenantScoped]
public class OscalDecompositionDraft
{
    /// <summary>
    /// FK to <see cref="Ato.Copilot.Core.Models.Tenancy.Tenant"/> — stamped
    /// automatically by <c>TenantStampingSaveChangesInterceptor</c> (Feature 048).
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>Unique identifier (GUID string, 36 chars).</summary>
    [Key]
    [MaxLength(36)]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>FK to RegisteredSystem.</summary>
    [Required]
    [MaxLength(36)]
    public string RegisteredSystemId { get; set; } = string.Empty;

    /// <summary>
    /// OSCAL control identifier (lowercase, e.g. "ac-1").
    /// Stored as received from the caller — must be lowercased before export.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string ControlId { get; set; } = string.Empty;

    /// <summary>Lifecycle status of this draft.</summary>
    [Required]
    public DecompositionDraftStatus Status { get; set; } = DecompositionDraftStatus.Pending;

    /// <summary>UTC timestamp when the AI decomposition was generated.</summary>
    [Required]
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UPN or OID of the user who triggered the decomposition.</summary>
    [Required]
    [MaxLength(254)]
    public string GeneratedBy { get; set; } = string.Empty;

    /// <summary>UPN or OID of the approver (null until approved).</summary>
    [MaxLength(254)]
    public string? ApprovedBy { get; set; }

    /// <summary>UTC timestamp of approval (null until approved).</summary>
    public DateTime? ApprovedAt { get; set; }

    // ─── Navigation ─────────────────────────────────────────────────────────

    /// <summary>Statement-level fragments generated by the AI decomposition pass.</summary>
    public List<OscalDecompositionFragment> Fragments { get; set; } = [];
}

/// <summary>
/// A single OSCAL statement-level fragment produced by an AI decomposition of
/// a control narrative. Belongs to one <see cref="OscalDecompositionDraft"/>.
/// </summary>
/// <remarks>
/// Feature 076 — T012. Each fragment maps to one OSCAL
/// <c>implemented-requirements[].statements[].by-components[]</c> entry.
/// </remarks>
[TenantScoped]
public class OscalDecompositionFragment
{
    /// <summary>
    /// FK to <see cref="Ato.Copilot.Core.Models.Tenancy.Tenant"/> — stamped
    /// automatically by <c>TenantStampingSaveChangesInterceptor</c> (Feature 048).
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>Unique identifier (GUID string, 36 chars).</summary>
    [Key]
    [MaxLength(36)]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>FK to the parent <see cref="OscalDecompositionDraft"/>.</summary>
    [Required]
    [MaxLength(36)]
    public string DraftId { get; set; } = string.Empty;

    /// <summary>
    /// OSCAL statement identifier, e.g. "ac-1_smt.a".
    /// Follows OSCAL 1.1.2 naming: {control-id}_smt.{part-letter}.
    /// </summary>
    [Required]
    [MaxLength(64)]
    public string StatementId { get; set; } = string.Empty;

    /// <summary>
    /// Optional UUID of the OSCAL component this fragment applies to.
    /// Null when the AI could not infer a specific component.
    /// </summary>
    [MaxLength(36)]
    public string? ComponentUuid { get; set; }

    /// <summary>
    /// AI-generated narrative text for this statement fragment.
    /// Written back to <see cref="ControlImplementation.Narrative"/> on approval.
    /// </summary>
    [Required]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// JSON-serialised list of AI-suggested parameter substitutions,
    /// e.g. <c>[{"param_id":"ac-1_prm_1","value":"annually"}]</c>.
    /// Null or "[]" when no parameters were suggested.
    /// </summary>
    [MaxLength(4000)]
    public string? SuggestedParamsJson { get; set; }

    /// <summary>
    /// AI confidence score for this fragment mapping (0.0–1.0), or <c>null</c> when the
    /// score could not be derived (fallback path). Always model self-reported — never
    /// an official ATO determination. Requires human review before use.
    /// </summary>
    public double? ConfidenceScore { get; set; }

    // ─── Navigation ─────────────────────────────────────────────────────────

    /// <summary>Parent decomposition draft.</summary>
    [ForeignKey(nameof(DraftId))]
    public OscalDecompositionDraft? Draft { get; set; }
}
