// Minimal vscode API stub for headless mocha runs in CI.
// Real VS Code APIs are available only inside an Electron-hosted extension host;
// this stub prevents "Cannot find module 'vscode'" when running mocha directly.
const vscode = {
  window: {
    showErrorMessage: () => {},
    showInformationMessage: () => {},
    showWarningMessage: () => {},
    showInputBox: () => Promise.resolve(undefined),
    showQuickPick: () => Promise.resolve(undefined),
    createOutputChannel: () => ({ appendLine: () => {}, show: () => {}, dispose: () => {} }),
    createWebviewPanel: () => ({ webview: { html: '', onDidReceiveMessage: () => ({ dispose: () => {} }), postMessage: () => {} }, onDidDispose: () => ({ dispose: () => {} }), reveal: () => {}, dispose: () => {} }),
    registerTreeDataProvider: () => ({ dispose: () => {} }),
    createTreeView: () => ({ dispose: () => {} }),
    activeTextEditor: undefined,
    visibleTextEditors: [],
    onDidChangeActiveTextEditor: () => ({ dispose: () => {} }),
  },
  workspace: {
    getConfiguration: () => ({ get: (key, def) => def, has: () => false, inspect: () => undefined, update: () => Promise.resolve() }),
    workspaceFolders: [],
    onDidChangeConfiguration: () => ({ dispose: () => {} }),
    onDidChangeWorkspaceFolders: () => ({ dispose: () => {} }),
    openTextDocument: () => Promise.resolve({}),
    findFiles: () => Promise.resolve([]),
    fs: { readFile: () => Promise.resolve(Buffer.from('')), writeFile: () => Promise.resolve(), stat: () => Promise.resolve({}) },
  },
  commands: {
    registerCommand: () => ({ dispose: () => {} }),
    executeCommand: () => Promise.resolve(),
    getCommands: () => Promise.resolve([]),
  },
  extensions: {
    getExtension: () => undefined,
    all: [],
  },
  languages: {
    registerCodeActionsProvider: () => ({ dispose: () => {} }),
    registerHoverProvider: () => ({ dispose: () => {} }),
    createDiagnosticCollection: () => ({ set: () => {}, delete: () => {}, clear: () => {}, dispose: () => {} }),
    getDiagnostics: () => [],
  },
  env: { machineId: 'test', sessionId: 'test', language: 'en', clipboard: { readText: () => Promise.resolve(''), writeText: () => Promise.resolve() } },
  EventEmitter: class { constructor() { this._listeners = []; this.event = (cb) => { this._listeners.push(cb); return { dispose: () => {} }; }; } fire(data) { this._listeners.forEach(l => l(data)); } dispose() {} },
  Uri: { file: (p) => ({ fsPath: p, scheme: 'file', path: p, toString: () => p }), parse: (s) => ({ toString: () => s }), joinPath: (base, ...parts) => ({ fsPath: [base.fsPath, ...parts].join('/'), toString: () => [base.toString(), ...parts].join('/') }) },
  Range: class { constructor(sl, sc, el, ec) { this.start = { line: sl, character: sc }; this.end = { line: el, character: ec }; } },
  Position: class { constructor(line, character) { this.line = line; this.character = character; } },
  Selection: class { constructor(al, ac, al2, ac2) {} },
  DiagnosticSeverity: { Error: 0, Warning: 1, Information: 2, Hint: 3 },
  CodeActionKind: { QuickFix: { value: 'quickfix', append: (s) => ({ value: 'quickfix.' + s }) }, Refactor: { value: 'refactor' }, Empty: { value: '' } },
  Diagnostic: class { constructor(range, message, severity) { this.range = range; this.message = message; this.severity = severity; } },
  CodeAction: class { constructor(title, kind) { this.title = title; this.kind = kind; } },
  ThemeIcon: class { constructor(id) { this.id = id; } },
  TreeItemCollapsibleState: { None: 0, Collapsed: 1, Expanded: 2 },
  TreeItem: class { constructor(label, collapsibleState) { this.label = label; this.collapsibleState = collapsibleState; } },
  StatusBarAlignment: { Left: 1, Right: 2 },
  ProgressLocation: { Notification: 15, Window: 10, SourceControl: 1 },
  ViewColumn: { One: 1, Two: 2, Three: 3, Active: -1 },
  ConfigurationTarget: { Global: 1, Workspace: 2, WorkspaceFolder: 3 },
  ExtensionContext: class {},
  CancellationTokenSource: class { constructor() { this.token = { isCancellationRequested: false, onCancellationRequested: () => ({ dispose: () => {} }) }; } cancel() {} dispose() {} },
  Disposable: { from: (...d) => ({ dispose: () => d.forEach(x => x.dispose()) }) },
  authentication: { getSession: () => Promise.resolve(null), onDidChangeSessions: () => ({ dispose: () => {} }) },
  l10n: { t: (s) => s },
};
module.exports = vscode;
