// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ato.Copilot.Core.Migrations
{
    /// <inheritdoc />
    public partial class Feature076_MakeConfidenceScoreNullable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // SQLite does not support ALTER COLUMN; rebuild the table to make ConfidenceScore nullable.
            migrationBuilder.Sql("PRAGMA foreign_keys = OFF;");

            migrationBuilder.Sql(@"
CREATE TABLE ""OscalDecompositionFragments_new"" (
    ""Id""                  TEXT NOT NULL CONSTRAINT ""PK_OscalDecompositionFragments"" PRIMARY KEY,
    ""TenantId""            TEXT NOT NULL,
    ""DraftId""             TEXT NOT NULL,
    ""StatementId""         TEXT NOT NULL,
    ""ComponentUuid""       TEXT,
    ""Description""         TEXT NOT NULL,
    ""SuggestedParamsJson"" TEXT,
    ""ConfidenceScore""     REAL,
    CONSTRAINT ""FK_OscalDecompositionFragments_OscalDecompositionDrafts_DraftId""
        FOREIGN KEY (""DraftId"") REFERENCES ""OscalDecompositionDrafts"" (""Id"") ON DELETE CASCADE
);");

            migrationBuilder.Sql(@"
INSERT INTO ""OscalDecompositionFragments_new""
    (""Id"", ""TenantId"", ""DraftId"", ""StatementId"", ""ComponentUuid"", ""Description"", ""SuggestedParamsJson"", ""ConfidenceScore"")
SELECT ""Id"", ""TenantId"", ""DraftId"", ""StatementId"", ""ComponentUuid"", ""Description"", ""SuggestedParamsJson"", ""ConfidenceScore""
FROM ""OscalDecompositionFragments"";");

            migrationBuilder.Sql(@"DROP TABLE ""OscalDecompositionFragments"";");
            migrationBuilder.Sql(@"ALTER TABLE ""OscalDecompositionFragments_new"" RENAME TO ""OscalDecompositionFragments"";");

            migrationBuilder.Sql("PRAGMA foreign_keys = ON;");

            migrationBuilder.CreateIndex(
                name: "IX_OscalDecompositionFragments_DraftId",
                table: "OscalDecompositionFragments",
                column: "DraftId");

            migrationBuilder.CreateIndex(
                name: "IX_OscalDecompositionFragments_Tenant_DraftId",
                table: "OscalDecompositionFragments",
                columns: new[] { "TenantId", "DraftId" });

            // Null out the placeholder confidence score (0.5 default) so callers know AI did not return a score.
            migrationBuilder.Sql(@"UPDATE ""OscalDecompositionFragments"" SET ""ConfidenceScore"" = NULL WHERE ""ConfidenceScore"" = 0;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_OscalDecompositionFragments_DraftId",
                table: "OscalDecompositionFragments");

            migrationBuilder.DropIndex(
                name: "IX_OscalDecompositionFragments_Tenant_DraftId",
                table: "OscalDecompositionFragments");

            // Rebuild with NOT NULL ConfidenceScore; replace any NULLs with 0.
            migrationBuilder.Sql("PRAGMA foreign_keys = OFF;");

            migrationBuilder.Sql(@"
CREATE TABLE ""OscalDecompositionFragments_old"" (
    ""Id""                  TEXT NOT NULL CONSTRAINT ""PK_OscalDecompositionFragments"" PRIMARY KEY,
    ""TenantId""            TEXT NOT NULL,
    ""DraftId""             TEXT NOT NULL,
    ""StatementId""         TEXT NOT NULL,
    ""ComponentUuid""       TEXT,
    ""Description""         TEXT NOT NULL,
    ""SuggestedParamsJson"" TEXT,
    ""ConfidenceScore""     REAL NOT NULL,
    CONSTRAINT ""FK_OscalDecompositionFragments_OscalDecompositionDrafts_DraftId""
        FOREIGN KEY (""DraftId"") REFERENCES ""OscalDecompositionDrafts"" (""Id"") ON DELETE CASCADE
);");

            migrationBuilder.Sql(@"
INSERT INTO ""OscalDecompositionFragments_old""
    (""Id"", ""TenantId"", ""DraftId"", ""StatementId"", ""ComponentUuid"", ""Description"", ""SuggestedParamsJson"", ""ConfidenceScore"")
SELECT ""Id"", ""TenantId"", ""DraftId"", ""StatementId"", ""ComponentUuid"", ""Description"", ""SuggestedParamsJson"", COALESCE(""ConfidenceScore"", 0.0)
FROM ""OscalDecompositionFragments"";");

            migrationBuilder.Sql(@"DROP TABLE ""OscalDecompositionFragments"";");
            migrationBuilder.Sql(@"ALTER TABLE ""OscalDecompositionFragments_old"" RENAME TO ""OscalDecompositionFragments"";");

            migrationBuilder.Sql("PRAGMA foreign_keys = ON;");

            migrationBuilder.CreateIndex(
                name: "IX_OscalDecompositionFragments_DraftId",
                table: "OscalDecompositionFragments",
                column: "DraftId");

            migrationBuilder.CreateIndex(
                name: "IX_OscalDecompositionFragments_Tenant_DraftId",
                table: "OscalDecompositionFragments",
                columns: new[] { "TenantId", "DraftId" });
        }
    }
}
